name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LOC_CHART: "False"
          SHOW_OPERATING_SYSTEMS: "True"
          SHOW_COMMIT: "True"
          LOCALE: "en"
